services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"   # REST (Python)
      - "6334:6334"   # gRPC (Java)
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
